# print report card of a student using variables and functions
Name = input("Enter your name: ")
Grade = int(input("Enter your grade: "))
Roll_Number = int(input("Enter your roll number: "))
Branch = input("Enter your branch: ")
science = float(input("Enter your science marks: "))
maths = float(input("Enter your maths marks: "))
english = float(input("Enter your english marks: "))
language = float(input("Enter your language marks: "))
computer = float(input("Enter your computer marks: "))
total = science + maths + english + language + computer
Percentage = total / 5
print ("*******************ID Card*************************")
print ("Name:", Name)
print ("Grade:", Grade)
print ("Roll Number:", Roll_Number)
print ("Branch:", Branch)
print ("____________Marks Obtained____________")
print ("Science:", science)
print ("Maths:", maths)
print ("English:", english)
print ("Language:", language)
print ("Computer:", computer)
print ("Total:", total)
print ("Percentage:", Percentage)
